all:
  vars:
    ansible_become_method: su
    # name of the database within postgres
    inprod_database_name: "inprod_prem"
    # postgres user that inprod-bow will use to connect as
    inprod_database_user: "inprod_user"
    # postgres user password that inprod-bow will use to connect as
    inprod_database_password: "PleaseReplaceMe"
    # the maximum size that the database schema is allowed to reach before auditing events are blocked. Match to 10% lower then the database mount point
    inprod_schema_size_mb: 20000
    inprod_email_domain: inprod.network
    inprod_email_host: smtp.sparkpostmail.com
    inprod_email_port: 587
    inprod_email_user: SMTP_Injection
    inprod_email_password: PleaseReplaceMe
    # Your license key that is set within the settings.json file
    inprod_license_key: PleaseReplaceMe
    # InProd yum repo token that is used to access the InProd RPM packages
    inprod_yum_token: "PleaseReplaceMe"


  hosts:
    192.168.20.206:
      host_name: inprod_sit
      inprod_database: "127.0.0.1"
      
      # database specific variables
      internal_ip_range: "192.168.20.0/24"
      postgresql_hba_entries:
        - { type: local, database: all, user: postgres, auth_method: peer }
        - { type: local, database: all, user: all, auth_method: peer }
        - { type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5 }
        - { type: host, database: all, user: all, address: '::1/128', auth_method: md5 }
        - { type: host, database: all, user: "{{ inprod_database_user }}", address: "{{ internal_ip_range }}", auth_method: md5 }
      # linux service account that postgres will run under, best not to change this
      postgresql_user: "postgres"
      # It best to use a different block storage device for the database for a number of reasons. Ensure this directory exists before running the playbook
      postgresql_mount_dir: "/mnt/postgres/pgsql"
      postgresql_data_dir: "{{ postgresql_mount_dir }}/data"
      postgresql_bin_path: "/opt/rh/rh-postgresql10/root/usr/bin"
