    - name: systemd reload
      become: true
      systemd:
        daemon_reload: yes

    - name: restart postgresql
      service:
        name: "rh-postgresql10-postgresql.service"
        state: "restarted"
 